files:
  include: 'sass/**/*.s+(a|c)ss'
rules:
  no-warn: 0
  no-color-keywords: 0
  no-color-literals: 0
  leading-zero:
    -
      include: true
  final-newline:
    -
      include: false
  brace-style:
    -
      allow-single-line: false
