sudo: false
language: node_js
node_js:
  - "4.3"
install:
  - npm install
cache:
  directories:
    - node_modules
    - $HOME/.nvm
script:
  - npm test
  - npm run lint
notifications:
  email: false
